### PR TITLE
add detector support for safari

### PR DESCRIPTION
**Pull request by wangzhen263**
I just add detector to support safari because safari returns window.URL as object not function in chrome. I and pete don't know how to run your test. Please do a test run. Thanks.

### CODE REVIEW

**Comment by DamonOehlman** [comment]
Thanks Jeff - I'll take a look soon :)

**Comment by geelen** [comment]
Might be better to replace this with

```
if (typeof scope[testName] == 'function' || typeof scope[testName] == 'object') {
```

**Comment by geelen** [comment]
Verified the above does work on current iOS Safari

**Comment by DamonOehlman** [comment]
Thanks @geelen - I'll make that change now.

**Comment by DamonOehlman** [comment]
did a bit of cleanup (addressed missing license as per #3) and published `1.0.1` :)

**Pull request closed without merging**
